#!/usr/bin/env php
<?php
/**
* FollowUpBoss: Real Estate Lead Management Software.
*
* @author        Anthony Gentile <anthony@followupboss.com>
* @copyright     Copyright (c) 2014, Enchant LLC.
* @license       Property of Enchant LLC. All rights reserved.
*/
namespace FUBSyntax;

error_reporting(E_ALL | E_STRICT);
set_time_limit(0);

require dirname(__FILE__) . '/vendor/autoload.php';
require dirname(__FILE__) . '/syntax.php';

use Aura\Cli\CliFactory;
use Aura\Cli\Status;
use Aura\Cli\Stdio\Formatter;
use Aura\Cli\Stdio\Handle;
use Aura\Cli\Stdio;

$stdin  = 'php://stdin';
$stdout = 'php://stdout';
$stderr = 'php://stderr';
$stdio = new Stdio(
    new Handle($stdin, 'r'),
    new Handle($stdout, 'w+'),
    new Handle($stderr, 'w+'),
    new Formatter
);

$cliFactory = new CliFactory;
$context = $cliFactory->newContext($GLOBALS);
$getopt = $context->getopt(array());

$pos = 1;
$checked = 0;
$errors = 0;

while (($path = $getopt->get($pos++))) {
    $syntax = new Syntax();
    if (!$syntax->run($path, $stdio)) {
        $errors++;
    }

    $checked++;
}

if (!$checked && !$path) {
    $stdio->errln("<<red>>Path to file/directory is required.<<reset>>");
    exit(Status::USAGE);
}

if ($errors > 0) {
    exit(Status::FAILURE);
} else {
    exit(Status::SUCCESS);
}
